// Code generated by cmd/gen-core-types. DO NOT EDIT.
//
// Source: internal/core (WorkItem, AgentRef, Relationship, Evidence,
// DefinitionOfDone, Sprint, TokenBudget, StateCategory).
//
// Regenerate with: make gen

export type WorkItemID = string;
export type AgentID = string;

export type StateCategory =
  | "backlog"
  | "unstarted"
  | "started"
  | "completed"
  | "canceled";

export const STATE_CATEGORIES: readonly StateCategory[] = [
  "backlog",
  "unstarted",
  "started",
  "completed",
  "canceled",
] as const;

export type RelationshipKind =
  | "blocks"
  | "parent_child"
  | "relates_to";

export type EvidenceKind =
  | "commit"
  | "log"
  | "test_result"
  | "url"
  | "file"
  | "custom";

export type BudgetTier = "inform" | "warn" | "stop";

export type AgentKind = "agent" | "human";

// AdaptorErrorKind is the closed discriminator every adaptor-boundary
// error carries (gm-faz). The SPA branches on _kind + retryable; it
// MUST NOT parse the human-readable message.
export type AdaptorErrorKind =
  | "validation"
  | "session_not_found"
  | "session_closed"
  | "request_failed"
  | "process_failed"
  | "rate_limited"
  | "unsupported"
  | "capability_denied"
  | "adaptor_degraded";

export const ADAPTOR_ERROR_KINDS: readonly AdaptorErrorKind[] = [
  "validation",
  "session_not_found",
  "session_closed",
  "request_failed",
  "process_failed",
  "rate_limited",
  "unsupported",
  "capability_denied",
  "adaptor_degraded",
] as const;

// AdaptorError is the wire shape emitted by every Go adaptor-boundary
// method on failure. The Go MarshalJSON flattens the typed Cause to a
// plain string so the SPA never has to walk an unknown error tree.
//
// Consumers branch on _kind for category and retryable for retry
// intent; all other fields are advisory.
export interface AdaptorError {
  _kind: AdaptorErrorKind;
  retryable: boolean;
  message: string;
  cause?: string;
  detail?: Record<string, unknown>;
}

export interface AgentRef {
  id: AgentID;
  name: string;
  agent_kind: AgentKind;
  parent_id?: AgentID | null;
  role?: string;
  workspace?: string;
}

export interface Relationship {
  kind: RelationshipKind;
  from: WorkItemID;
  to: WorkItemID;
}

export interface Evidence {
  id: string;
  kind: EvidenceKind;
  source: string;
  ref?: string;
  summary?: string;
  captured_at: string;
  payload?: Record<string, unknown>;
}

export interface DefinitionOfDone {
  acceptance_criteria: string[];
  notes?: string;
  version?: string;
}

export interface TokenBudget {
  limit: number;
  used: number;
  inform: number;
  warn: number;
  stop: number;
}

export interface Sprint {
  id: string;
  name: string;
  starts_at: string;
  ends_at: string;
  goal?: string;
  work_items?: WorkItemID[];
  budget?: TokenBudget | null;
}

export interface WorkItem {
  id: WorkItemID;
  kind: string;
  title: string;
  description?: string;
  status: string;
  state_category: StateCategory;
  priority?: number | null;
  owner?: AgentRef | null;
  assignee?: AgentRef | null;
  labels?: string[];
  relationships?: Relationship[];
  evidence?: Evidence[];
  dod?: DefinitionOfDone | null;
  sprint_id?: string | null;
  created_at: string;
  updated_at: string;
  custom?: Record<string, unknown>;
}
