// Code generated by cmd/gen-core-types. DO NOT EDIT.
//
// Source: internal/core (WorkItem, AgentRef, Relationship, Evidence,
// DefinitionOfDone, Sprint, TokenBudget, StateCategory, Flags,
// CapabilityManifest + extensions).
//
// Regenerate with: make gen

export type WorkItemID = string;
export type AgentID = string;

export type StateCategory =
  | "backlog"
  | "unstarted"
  | "staged"
  | "started"
  | "completed"
  | "canceled";

export const STATE_CATEGORIES: readonly StateCategory[] = [
  "backlog",
  "unstarted",
  "staged",
  "started",
  "completed",
  "canceled",
] as const;

export type RelationshipKind =
  | "blocks"
  | "parent_child"
  | "relates_to";

export type EvidenceKind =
  | "commit"
  | "log"
  | "test_result"
  | "url"
  | "file"
  | "custom";

// KIND_MILESTONE is the canonical WorkItem.kind token for milestones
// (gm-root.3). WorkItem.kind is a free string because adaptors emit
// kinds beyond the core's knowledge, so this is an exported constant
// rather than a union variant. SPA code that gates on "is this a
// milestone?" MUST compare against KIND_MILESTONE rather than
// hardcoding the literal.
export const KIND_MILESTONE = "milestone";

// SessionStatus is the observable session lifecycle tag (gm-d044).
// The SPA uses it to render the per-session badge on the board + drawer
// (gm-r1l1). Suspended is the only non-observable value; it's kept for
// the pre-existing Pause/Resume flow and sits outside the
// initializing/ready/working/prompting observable set.
export type SessionStatus =
  | "initializing"
  | "ready"
  | "working"
  | "prompting"
  | "stalled"
  | "suspended"
  | "completed"
  | "failed";

export const SESSION_STATUSES: readonly SessionStatus[] = [
  "initializing",
  "ready",
  "working",
  "prompting",
  "stalled",
  "suspended",
  "completed",
  "failed",
] as const;

export type BudgetTier = "inform" | "warn" | "stop";

export type AgentKind = "agent" | "human";

export type Transport = "api" | "jsonl" | "mcp";

export const TRANSPORTS: readonly Transport[] = [
  "api",
  "jsonl",
  "mcp",
] as const;

// StateMap is the adaptor's declarative translation from its native
// status tokens to the five core StateCategory buckets. Required on
// every CapabilityManifest.
export type StateMap = Record<string, StateCategory>;

// Capability-manifest string-literal enums (R1–R8 fields, gm-knrm).
// Mirror the Go-side authoritative sets in internal/core/workplane.go;
// keep in lockstep — the Validate() calls there enforce the same set.
//
// Generated as plain string-literal unions rather than full enums so
// the SPA can pattern-match exhaustively. New variants must land in
// both the Go const block AND here, in the same order, so the manifest
// round-trip parity tests stay honest.
export type SchemaEnforcement =
  | "native"
  | "synthesized";

export type QueryLanguage =
  | "filter-only"
  | "jsonpath"
  | "sql-subset"
  | "graphql";

export type VersioningTransport =
  | "none"
  | "git"
  | "dolt"
  | "jsonl"
  | "native-sqlite-export";

export type ConcurrencyModel =
  | "optimistic"
  | "mvcc"
  | "git-merge"
  | "dolt-merge";

export type AgentNativeAPI =
  | "cli"
  | "json-api"
  | "mcp"
  | "rest-only";

export type OrchestratorHook =
  | "ready-set-subscribe"
  | "claim-atomic"
  | "escalation-ingest"
  | "work-complete-ack"
  | "pool-bulk-dispatch";

// AdaptorErrorKind is the closed discriminator every adaptor-boundary
// error carries (gm-faz). The SPA branches on _kind + retryable; it
// MUST NOT parse the human-readable message.
export type AdaptorErrorKind =
  | "validation"
  | "session_not_found"
  | "session_closed"
  | "request_failed"
  | "process_failed"
  | "rate_limited"
  | "unsupported"
  | "capability_denied"
  | "adaptor_degraded"
  | "read_only";

export const ADAPTOR_ERROR_KINDS: readonly AdaptorErrorKind[] = [
  "validation",
  "session_not_found",
  "session_closed",
  "request_failed",
  "process_failed",
  "rate_limited",
  "unsupported",
  "capability_denied",
  "adaptor_degraded",
  "read_only",
] as const;

// AdaptorError is the wire shape emitted by every Go adaptor-boundary
// method on failure. The Go MarshalJSON flattens the typed Cause to a
// plain string so the SPA never has to walk an unknown error tree.
//
// Consumers branch on _kind for category and retryable for retry
// intent; all other fields are advisory.
export interface AdaptorError {
  _kind: AdaptorErrorKind;
  retryable: boolean;
  message: string;
  cause?: string;
  detail?: Record<string, unknown>;
}

export interface AgentRef {
  id: AgentID;
  name: string;
  agent_kind: AgentKind;
  parent_id?: AgentID | null;
  role?: string;
  workspace?: string;
  dialect?: string | null;
}

export interface Relationship {
  kind: RelationshipKind;
  from: WorkItemID;
  to: WorkItemID;
}

export interface Evidence {
  id: string;
  kind: EvidenceKind;
  source: string;
  ref?: string;
  summary?: string;
  captured_at: string;
  payload?: Record<string, unknown>;
}

export interface DefinitionOfDone {
  acceptance_criteria: string[];
  notes?: string;
  version?: string;
}

export interface TokenBudget {
  limit: number;
  used: number;
  inform: number;
  warn: number;
  stop: number;
}

export interface Sprint {
  id: string;
  name: string;
  starts_at: string;
  ends_at: string;
  goal?: string;
  work_items?: WorkItemID[];
  budget?: TokenBudget | null;
}

// DerivedSignals are UI-facing booleans computed by the server from a
// WorkItem plus its open escalations (gm-gsh). They answer the three
// questions the Kanban / backlog / agents dashboards ask most often;
// consumers MUST treat them as pure-derived cache values and re-derive
// locally rather than persisting them. Emitted on WorkItem.derived.
export interface DerivedSignals {
  agent_claimable: boolean;
  human_action_required: boolean;
  review_pending: boolean;
}

export interface WorkItem {
  id: WorkItemID;
  repository_id?: RepositoryID;
  kind: string;
  title: string;
  description?: string;
  status: string;
  state_category: StateCategory;
  priority?: number | null;
  owner?: AgentRef | null;
  assignee?: AgentRef | null;
  labels?: string[];
  relationships?: Relationship[];
  evidence?: Evidence[];
  dod?: DefinitionOfDone | null;
  sprint_id?: string | null;
  created_at: string;
  updated_at: string;
  custom?: Record<string, unknown>;
  derived?: DerivedSignals | null;
}

// Flags is the flat-boolean projection of a CapabilityManifest intended
// for UI gating (see internal/core/manifest.go). The rich manifest is
// kept for server-side decisions; Flags is what <Capability has="..."/>
// consumes in the SPA. Deterministic: derive it from the manifest on
// every render rather than caching it across reconnects.
export interface Flags {
  has_sprints: boolean;
  has_budget: boolean;
  has_evidence: boolean;
  has_declared_state: boolean;
  has_extension_edges: boolean;
  has_extension_fields: boolean;
  has_extension_rel_fields: boolean;
}

// FieldExtension declares an adaptor-native field that core does not
// know about. The UI only renders it inside
// web/src/extensions/<adaptor-id>/ (gm-root DD-4).
export interface FieldExtension {
  name: string;
  type: string;
  description?: string;
}

// EdgeExtension declares an adaptor-native relationship kind that is
// not one of the three core edges (gm-root DD-9). The UI falls back to
// "relates_to" semantics when the adaptor's extension widget is absent.
export interface EdgeExtension {
  name: string;
  directed: boolean;
  inverse?: string;
  description?: string;
}

// RelationshipExtension declares an adaptor-native field on the
// Relationship record itself (not a new edge kind).
export interface RelationshipExtension {
  name: string;
  type: string;
  description?: string;
}

// CapabilityManifest is the declarative description every WorkPlane
// adaptor returns from Describe. It tells core (and the UI) which
// transport the adaptor speaks, how to normalize its native statuses,
// what extensions it carries beyond the core primitives, and which
// optional feature groups it opts into (gm-root DD-15).
export interface CapabilityManifest {
  adaptor_name: string;
  adaptor_version: string;
  protocol_version: string;
  transport: Transport;
  state_map: StateMap;
  edge_extensions?: EdgeExtension[];
  field_extensions?: FieldExtension[];
  relationship_extensions?: RelationshipExtension[];
  sprint_native: boolean;
  token_budget_enforced: boolean;
  evidence_synthesis_required: boolean;
  read_only: boolean;
  description_format?: string;
  schema_enforcement?: SchemaEnforcement;
  query_languages?: QueryLanguage[];
  dependency_graph_native?: boolean;
  ready_set_query?: boolean;
  versioning_transport?: VersioningTransport[];
  concurrency_model?: ConcurrencyModel;
  agent_session_decoupling?: boolean;
  agent_native_api?: AgentNativeAPI;
  orchestrator_hooks?: OrchestratorHook[];
}

// FLAG_NAMES is the exhaustive list of keys on Flags. Useful for
// exhaustiveness checks in the SPA's gating layer (so a new flag added
// on the Go side surfaces as a type error on the UI side).
export const FLAG_NAMES = [
  "has_sprints",
  "has_budget",
  "has_evidence",
  "has_declared_state",
  "has_extension_edges",
  "has_extension_fields",
  "has_extension_rel_fields",
] as const;

export type FlagName = (typeof FLAG_NAMES)[number];
