// Package client is the typed Go HTTP client for the gemba server API
// (gm-o9t8.1.1.4).
//
// The low-level surface (one method per OpenAPI operationId) is
// generated by oapi-codegen from the spec the server itself serves at
// /api/openapi.json (source: internal/server/openapi/openapi.json).
// The generated code lives in the `gen` subpackage and MUST NOT be
// edited by hand; run `go generate ./internal/client/...` to refresh
// it after the spec changes.
//
// On top of the generated client, this package adds three concerns the
// raw codegen output doesn't cover:
//
//  1. Auth header injection. New() consults the credstore
//     (internal/auth/credstore) for the requested server URL and
//     attaches `Authorization: Bearer <token>` to every outbound call.
//     Callers may override the token explicitly with WithToken.
//
//  2. X-GEMBA-Confirm nonce. State-mutating verbs (POST/PATCH/DELETE)
//     on the Govern surface require a one-shot UUID nonce; the wrapper
//     generates one per request so callers never have to think about
//     it. GET / HEAD / OPTIONS calls do NOT get the header so they
//     stay cacheable.
//
//  3. Error envelope mapping. The server returns a stable JSON envelope
//     (`{"error":"...","message":"..."}` per the OpenAPI `Error`
//     component) for 4xx / 5xx responses. errors.go parses this and
//     surfaces typed sentinels (ErrUnauthorized, ErrNotFound,
//     ErrConflict, ErrNotImplemented, ErrBadRequest) plus a generic
//     `*ServerError` for everything else.
package client

//go:generate go run preprocess_spec.go ../server/openapi/openapi.json gen/openapi-3.0.json
//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen -config oapi-codegen.yaml gen/openapi-3.0.json
