// Package core: see doc.go for the overview.
package core

// CoreTypesTS is the adaptor-agnostic domain surface expressed in
// TypeScript. It is the single source of truth that drives the generated
// `web/src/types/core.gen.ts`; keep the shapes byte-for-byte in sync
// with the Go definitions in this package.
//
// This string is emitted verbatim by `cmd/gen-core-types`; tests in this
// package assert the shape-level parity against the Go types. The file
// under web/ should only be regenerated via `go generate ./internal/core`
// (or `make gen`) so that humans don't hand-edit a generated artifact.
const CoreTypesTS = `// Code generated by cmd/gen-core-types. DO NOT EDIT.
//
// Source: internal/core (WorkItem, AgentRef, Relationship, Evidence,
// DefinitionOfDone, Sprint, TokenBudget, StateCategory).
//
// Regenerate with: make gen

export type WorkItemID = string;
export type AgentID = string;

export type StateCategory =
  | "backlog"
  | "unstarted"
  | "started"
  | "completed"
  | "canceled";

export const STATE_CATEGORIES: readonly StateCategory[] = [
  "backlog",
  "unstarted",
  "started",
  "completed",
  "canceled",
] as const;

export type RelationshipKind =
  | "blocks"
  | "depends_on"
  | "parent_of"
  | "child_of"
  | "related";

export type EvidenceKind =
  | "commit"
  | "log"
  | "test_result"
  | "url"
  | "file"
  | "custom";

export type BudgetTier = "inform" | "warn" | "stop";

export interface AgentRef {
  id: AgentID;
  name: string;
  role?: string;
  workspace?: string;
}

export interface Relationship {
  kind: RelationshipKind;
  from: WorkItemID;
  to: WorkItemID;
}

export interface Evidence {
  id: string;
  kind: EvidenceKind;
  source: string;
  ref?: string;
  summary?: string;
  captured_at: string;
  payload?: Record<string, unknown>;
}

export interface DefinitionOfDone {
  acceptance_criteria: string[];
  notes?: string;
  version?: string;
}

export interface TokenBudget {
  limit: number;
  used: number;
  inform: number;
  warn: number;
  stop: number;
}

export interface Sprint {
  id: string;
  name: string;
  starts_at: string;
  ends_at: string;
  goal?: string;
  work_items?: WorkItemID[];
  budget?: TokenBudget | null;
}

export interface WorkItem {
  id: WorkItemID;
  kind: string;
  title: string;
  description?: string;
  status: string;
  state_category: StateCategory;
  priority?: number | null;
  owner?: AgentRef | null;
  assignee?: AgentRef | null;
  labels?: string[];
  relationships?: Relationship[];
  evidence?: Evidence[];
  dod?: DefinitionOfDone | null;
  sprint_id?: string | null;
  created_at: string;
  updated_at: string;
  custom?: Record<string, unknown>;
}
`
